### ISSUE TITLE
URL にリンクを張りたい

### ISSUE THREAD

**Issue by kawmra** [kawmra/Rooster#12]
タスク一覧の URL にハイパーリンクを張りたい

**Comment by shun-komaki** [comment]
こうゆうこと？

![image](https://user-images.githubusercontent.com/11956771/49281911-202d9300-f4d1-11e8-8f3b-5da54e3cfdf4.png)

![image](https://user-images.githubusercontent.com/11956771/49281944-39ceda80-f4d1-11e8-814b-8cce38815970.png)

**Comment by kawmra** [comment]
@shun-komaki
そういうことです！！！
